"""
Django settings for newspaperproject project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r_l0^=a4j_b0+)mkpkua9=0i8l41rqzzo!rt)*@7@$)+g^#07*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'django_filters',
    'django_apscheduler',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'newspaperapp',
    'sign',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newspaperproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'newspaperproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/sign'

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_FORMS = {'signup': 'sign.forms.CommonSignupForm'}

# настройка email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'm.pws.g.acc@gmail.com'
EMAIL_HOST_PASSWORD = 'anjovjitlbblgsji'

EMAIL_SERVER = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = ['m.pws.g.acc@gmail.com']

ACCOUNT_CONFIRM_EMAIL_ON_GET = True

APSCHEDULER_DATETIME_FORMAT = 'N j, Y, f:s a'
APSCHEDULER_RUN_NOW_TIMEOUT = 25

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "console_debug_formatter": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
        "console_warning_formatter": {
            "format": "{asctime} {levelname} {message} {pathname}",
            "style": "{",
        },
        "console_error_formatter": {
            "format": "{asctime} {levelname} {message} {pathname} {exc_info}",
            "style": "{",
        },
        "file_general_log_formatter": {
            "format": "{asctime} {levelname} {module} {message}",
            "style": "{",
        },
        "file_errors_log_formatter": {
            "format": "{asctime} {levelname} {message} {pathname} {exc_info}",
            "style": "{",
        },
        "file_security_log_formatter": {
            "format": "{asctime} {levelname} {module} {message}",
            "style": "{",
        },
        "mail_admins_formatter": {
            "format": "{asctime} {levelname} {message} {pathname}",
            "style": "{",
        }
    },

    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_or_info_level": {
            "()": "newspaperproject.custom_log_filters.RequireDebugOrInfoLevel",
        },
        "require_warning_level": {
            "()": "newspaperproject.custom_log_filters.RequireWarningLevel",
        },
        "require_error_or_critical_level": {
            "()": "newspaperproject.custom_log_filters.RequireErrorOrCriticalLevel",
        },
    },

    "handlers": {
        "console_debug": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "console_debug_formatter",
            "filters": ["require_debug_true", "require_debug_or_info_level"],
        },
        "console_warning": {
            "class": "logging.StreamHandler",
            "level": "WARNING",
            "formatter": "console_warning_formatter",
            "filters": ["require_debug_true", "require_warning_level"],
        },
        "console_error": {
            "class": "logging.StreamHandler",
            "level": "ERROR",
            "formatter": "console_error_formatter",
            "filters": ["require_debug_true", "require_error_or_critical_level"],
        },
        "file_general_log": {
            "class": "logging.FileHandler",
            "filename": "log_files/general.log",
            "level": "INFO",
            "formatter": "file_general_log_formatter",
            "filters": ["require_debug_false"]
        },
        "file_errors_log": {
            "class": "logging.FileHandler",
            "filename": "log_files/errors.log",
            "level": "ERROR",
            "formatter": "file_errors_log_formatter",
        },
        "file_security_log": {
            "class": "logging.FileHandler",
            "filename": "log_files/security.log",
            "level": "INFO",
            "formatter": "file_security_log_formatter",
        },
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "level": "ERROR",
            "formatter": "mail_admins_formatter",
            "filters": ["require_debug_false"],
        },
    },

    "loggers": {
        "django": {
            "handlers": ["console_debug", "console_warning", "console_error", "file_general_log"],
            "propagate": True,
        },
        "django.request": {
            "handlers": ["file_errors_log", "mail_admins"],
            "propagate": True,
        },
        "django.server": {
            "handlers": ["file_errors_log", "mail_admins"],
            "propagate": True,
        },
        "django.template": {
            "handlers": ["file_errors_log"],
            "propagate": True,
        },
        "django.db_backends": {
            "handlers": ["file_errors_log"],
            "propagate": True,
        },
        "django.security": {
            "handlers": ["file_security_log"],
            "propagate": True,
        },
    },
}
