# Generated by Django 4.2.1 on 2023-05-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThtough',
            new_name='postThrough',
        ),
    ]
