# Generated by Django 4.2.1 on 2023-05-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0002_migr20052023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='postType',
        ),
    ]
