# Generated by Django 4.2.1 on 2023-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0003_migration200520232251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Здесь будет текст статьи(новости)...'),
        ),
    ]
